### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by superasty** [eu-digital-green-certificates/dgca-verifier-app-android#182] opened 2021-08-06 01:25 UTC
Could the front camera be used for the scanner?
How could this be done?

Regards
Fabio

**Comment by daniel-eder** [comment] 2021-08-06 06:10
Duplicate of #95 
See specifically https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/issues/95#issuecomment-869633164

**Closed by daniel-eder** 2021-08-06 06:10 UTC
Labels: duplicate, question
