### ISSUE TITLE
Spanish "comunitat valenciana" certificate not validating

### ISSUE THREAD

**Issue by rampa069** [eu-digital-green-certificates/dgca-verifier-app-android#116] opened 2021-06-26 09:31 UTC
## Describe the bug

Scanning my own vaccination certificate results in FAILED verification.

## Expected behaviour

Should be verified.

## Steps to reproduce the issue

fails scanning any certificate downloaded from  the "comunidad valenciana" health web site.

  Decoding manually the CBOR records, can see a difference in the "6" field. In this certificates, thy used a decimal point in the expiration date.
{
    "1": "ES",
    "4": 1685271300,
    "6": 1624617519.261,
 
Also i have a problem verifying the signature:

KeyError: 'Key ID not found in cert list: 65c7e496812f7c64'
-->

## Technical details

Android Xiaomi POCO X3

## Possible Fix

1. fix the decimal point in the timestamp field (not in your app, but dont know how to open a issue about this)
2. add the valencian healt certificate to the permited issuers.

**Comment by SchulzeStTSI** [comment] 2021-06-27 22:08
@rampa069 Do you scan a productive certificate where this problem with the fractional seconds occur? If yes, you should address this with a new issue  in the quality assurance repository.  If this is not a productive code, please transmit us in the same repository directly the QR for investigation. We will contact  then your national representives to investigate more in this issue to trigger the bug fixing of the certificate issuer.

**Comment by rampa069** [comment] 2021-06-28 07:33
yes, it is a real covid certification.

  yesterday i asked for another (this time not to the valencian authority but the national one)  and also does not validate.

In this one, the timestamp is correct, but still invalid.... decoding this cert, it has KID a85345d9d0be9a34.

may be spain is not uploading his certs to the gateway? 

if you need both png, let me know how to send it to you.  where is the QA repo? is it the testng-data?

**Comment by rampa069** [comment] 2021-06-28 07:37
failing with this one, may be related to #94 and not with the valencian one as i assumed at the beginning.

**Comment by SchulzeStTSI** [comment] 2021-06-28 07:58
@rampa069 It's this repository: https://github.com/eu-digital-green-certificates/dcc-quality-assurance There you can report productive QR Code anomalies. Can you please reopen the ticket there? (with links to the other two). Thanks for reporting that.

**Comment by kerstin-oppermann-tsi** [comment] 2021-06-29 14:59
We will close this ticket because the problem is, that our template apps do not run against a production environment.

See last comment in https://github.com/eu-digital-green-certificates/dcc-quality-assurance/issues/60

**Closed by kerstin-oppermann-tsi** 2021-06-29 14:59 UTC
Labels: bug
