### ISSUE TITLE
Certificate reload in app results in invalide certificate scanning (verification failed)

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-verifier-app-android#83] opened 2021-06-08 09:06 UTC
**Environment:**
Android Phone
Android Verifier App 1.0.3-acc

**Steps:**

1. Deinstall old verifier apps
2. Install app-acc-release-signed-1.0.3.apk (https://github.com/eu-digital-green-certificates/dgca-wallet-app-android/releases/tag/1.0.3)
3. Scan certificate 
     in this case 
![image](https://user-images.githubusercontent.com/81565834/121154184-0b22df00-c847-11eb-955c-a2e71597e1a0.png)
-> in this case all three are valid (green)
4. click on the 3 points (settings) in the app
5. tap on RELOAD button
6. Scan the same certificates
-> all 3 certificates are in status "Verification failed"

**Comment by oleksandrsarapulovgl** [comment] 2021-06-09 08:57
@kerstin-oppermann-tsi I've just tried it, and was not able to reproduce. In accordance to discussions with other devs, it seemed there was some issue on BE side that supposed to be fixed now.

@kerstin-oppermann-tsi could you please check it once again on the same build? It should be working now.

FYI @joerg-oppermann-tsi @Hendrik-Schmidt-Schierhorn-TSI

**Comment by kerstin-oppermann-tsi** [comment] 2021-06-09 09:11
@oleksandrsarapulovgl thanks, I checked the issue again and no it works fine !!

**Closed** 2021-06-09 09:24 UTC
Labels: 1st Prio - High, bug
