### ISSUE TITLE
Test Certificates - "Date of Collection" and "Date of Test Result" values not displayed

### ISSUE THREAD

**Issue by sokkphoto** [eu-digital-green-certificates/dgca-verifier-app-android#45] opened 2021-05-21 11:47 UTC
This relates to https://github.com/eu-digital-green-certificates/dgc-testdata/issues/30 opened by @martin-lindstrom

**Verification App (Android, potentially iOS also)** - Seems the "dr" and "sc" fields are not displayed by the Android Verification App (did not test with iOS).

**Issuance Service** - The labeling used in the CBOR is not fully compliant with RFC8949 3.4.1 (https://www.rfc-editor.org/rfc/rfc8949.html#name-standard-date-time-string)

## To reproduce
- Scan a test-type certificate with the template verifier app (tested with Android currently),
e.g. https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/BE/png/3.png

## Currently
- The "Date of Collection" and "Date of Test Result" are displayed empty, although the data is present in the QR.

Note that currently in the QRs generated, the CBOR includes the "dr" and "sc" fields non-tagged, while RFC8949 (3.4.1) specifies tag 0 to be used.
See https://www.rfc-editor.org/rfc/rfc8949.html#name-standard-date-time-string

Tested also with tag 0. If tag 0 IS used in the CBOR/QR (according to RFC8949), then Verification App behavior is still not correct.

Input QR: 
<img src="https://user-images.githubusercontent.com/26298336/119132337-3f269380-ba43-11eb-9475-d835831c8860.png" width="300" />

Verification app: 
<img src="https://user-images.githubusercontent.com/26298336/119132421-55ccea80-ba43-11eb-9f86-f96db6f3f9ba.png" width="300" />

### Verification app
- The "Date of Collection" and "Date of Test Result" are displayed correctly with the template dgca-verifier-app-android app, when a QR is scanned that 
-- conforms to the schema (and references) at https://github.com/eu-digital-green-certificates/ehn-dgc-schema
-- was created with dgca-issuance-service

### Issuance Service
- QRs are generated with datetime string fields tagged with "0", as specified in RFC8949 3.4.1 (https://www.rfc-editor.org/rfc/rfc8949.html#name-standard-date-time-string)

## Points of contact at the Estonian development teams
- Issuance (Guardtime Estonia) - @sokkphoto - Jaan Sokk; @martti007 - Martti Marran
- Verification (Nortal) - @tanelkaar - Tanel Käär

**Comment by fneur** [comment] 2021-05-21 14:31
@sokkphoto 
The problem is due to a java.text.ParseException: Unparseable date: "2021-05-19T08:20:00Z"
![image](https://user-images.githubusercontent.com/33552046/119153543-a2b7bd80-ba51-11eb-9adf-7bf9eee40a3e.png)

**Comment by fneur** [comment] 2021-05-22 18:02
Fixed by PR: #46

**Comment by sokkphoto** [comment] 2021-05-25 03:46
Thanks!

**Comment by oleksandrsarapulovgl** [comment] 2021-05-27 06:42
Fixed with PR: https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/pull/53

**Closed** 2021-05-27 07:41 UTC
Labels: bug
